name: Daily Web Scraper

on:
  schedule:
    # this runs at 8:00 AM UTC (1:00 AM Eastern Time), every day, from October through April
    - cron: '0 8 * 10-4 *'
  workflow_dispatch: # this adds a "Run Now" button in GitHub for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python nba_screener/nba_screener.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sqlite/data.sqlite
          # the "|| exit 0" prevents the action from failing if no data changed
          git commit -m "Automated data update" || exit 0
          git push
